import {
  MonitorCheck,
  TabletSmartphoneIcon,
  AppWindow,
  ArrowLeft,
  Boxes,
  CalendarRange,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronsUpDown,
  FileText,
  LayoutDashboard,
  Loader2,
  Loader,
  LogOut,
  Menu,
  MoreHorizontal,
  PenSquare,
  Plus,
  PlusCircle,
  PlusSquare,
  Stethoscope,
  Table2,
  Trash2,
  UserCircle2,
  Users,
  Workflow,
  X,
  XCircle,
  Info,
  Search,
  User2,
  Blinds,
  Home,
  ClipboardList,
  TrafficCone,
  Timer,
  LineChart,
  Github,
} from 'lucide-react';

export const Icons = {
  close: X,
  checkCirle: CheckCircle,
  dashboard: LayoutDashboard,
  program: AppWindow,
  patient: Users,
  user: UserCircle2,
  practitioner: Stethoscope,
  planning: CalendarRange,
  profile: UserCircle2,
  logout: LogOut,
  plus: Plus,
  menu: Menu,
  delete: XCircle,
  file: FileText,
  edit: PenSquare,
  activity: Workflow,
  add: PlusCircle,
  trash: Trash2,
  spinner: Loader2,
  loader: Loader,
  more: MoreHorizontal,
  check: Check,
  chevronsupdown: ChevronsUpDown,
  plusSquare: PlusSquare,
  arrowLeft: ArrowLeft,
  table: Table2,
  chevronDown: ChevronDown,
  logo: Boxes,
  info: Info,
  search: Search,
  user2: User2,
  blinds: Blinds,
  home: Home,
  clipboardlist: ClipboardList,
  trafficCone: TrafficCone,
  timer: Timer,
  responsive: TabletSmartphoneIcon,
  moniter: MonitorCheck,
  linechart: LineChart,
  gitHub: Github,
};
